apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 486471633519.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
          ports:
            - containerPort: 8080