name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn clean package

      - name: Test
        run: mvn test
        
        # ---------------- SONARQUBE ----------------
      - name: SonarQube Scan
        run: mvn sonar:sonar \
            -Dsonar.projectKey=my-app \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
            scanMetadataReportFile: target/sonar/report-task.txt
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker
        run: docker build -t app .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Tag Image
        run: docker tag app:latest 486471633519.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

      - name: Push Image
        run: docker push 486471633519.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name my-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false